### ISSUE TITLE
Step #0: No .deps.json file found for the app

### ISSUE THREAD

**Issue by juankibin** [googleapis/google-cloud-dotnet#4956]
I'm trying to make CI/CD from Gitlab to GCP. My project is a dotnet core and this is my setup
of .gitlab-ci.yml
```
image: microsoft/dotnet:latest

before_script:
  - echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - apt-get update
  - apt-get -qq -y install google-cloud-sdk

stages:
  - build
  - test
  - release
  
build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test
    
release:
  stage: release
  only:
    - dev-cloud-preparation
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy app.yaml
```
But I'm encountering this error 

 Step #0: Digest: sha256:8d4c52a5dc924d7f7651977fb04003f383e9898e7cc625340b3af86a55450738
 Step #0: Status: Downloaded newer image for gcr.io/gcp-runtimes/aspnetcorebuild@sha256:8d4c52a5dc924d7f7651977fb04003f383e9898e7cc625340b3af86a55450738
 Step #0: gcr.io/gcp-runtimes/aspnetcorebuild@sha256:8d4c52a5dc924d7f7651977fb04003f383e9898e7cc625340b3af86a55450738
 Step #0: No .deps.json file found for the app
 Finished Step #0
 ERROR
 ERROR: build step 0 "gcr.io/gcp-runtimes/aspnetcorebuild@sha256:8d4c52a5dc924d7f7651977fb04003f383e9898e7cc625340b3af86a55450738" failed: step exited with non-zero status: 1
 --------------------------------------------------------------------------------
 ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/cloud-build/builds/0d6b373b-6df9-4609-8716-a0a46cc58d21?project=667815729729 Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs for details
Running after_script
00:01
Uploading artifacts for failed job
00:02
 ERROR: Job failed: exit code 1

How can I solve this , it almost 1 week making this CI/CD please help.
THanks
