### ISSUE TITLE
Spanner xref not linking properly

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-dotnet#6741]
Sample:
https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Spanner.Admin.Database.V1/latest/Google.Cloud.Spanner.Admin.Database.V1.Database#Google_Cloud_Spanner_Admin_Database_V1_Database_DatabaseName

That should link to https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Spanner.Common.V1/latest/Google.Cloud.Spanner.Common.V1.DatabaseName

It's unclear as yet where the problem is.

**Comment by jskeet** [comment]
Curiouser and curiouser - I'd expected that this was a problem of the Google.Cloud.Spanner.Common.V1 xrefmap not being available at build time, but rebuilding the HTML now yields the same output :(

**Comment by jskeet** [comment]
I can reproduce this locally, and indeed see *some* of the same failures with protobuf xrefs. Oddly enough, the Google.Protobuf.WellKnownTypes.Timestamp references in Backup seem to be okay on the [cloud.google.com doc](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Spanner.Admin.Database.V1/latest/Google.Cloud.Spanner.Admin.Database.V1.Backup) but not when building locally... even though some *other* protobuf types are okay.

I'm getting very confused...

**Comment by jskeet** [comment]
Progress: I *believe* it's due to the Google.Cloud.Spanner.Common.V1 reference being via a ProjectReference instead of a PackageReference. I now need to diff the yaml outputs...

**Comment by jskeet** [comment]
Further oddity - *sometimes*, names have the "Google" part truncated; other times only the short name is used, e.g. "Protobuf.WellKnownTypes.Timestamp" vs "Timestamp".

Still trying to work out why that is...

**Comment by jskeet** [comment]
Okay, I now somewhat understand the linking part (but not the weird name truncation part).

In the YAML file, there's a `references` section, like this:

```yaml
references:
- uid: Google.Cloud.Spanner.Admin.Database.V1
  commentId: N:Google.Cloud.Spanner.Admin.Database.V1
  name: Google.Cloud.Spanner.Admin.Database.V1
  nameWithType: Google.Cloud.Spanner.Admin.Database.V1
  fullName: Google.Cloud.Spanner.Admin.Database.V1
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
```

(But much longer.)

Any types brought in via `PackageReference` have `isExternal: true` in the entry. Any brought in via `ProjectReference` don't have an `isExternal` at all. I believe xrefs are only evaluated against entries with `isExternal: true`.

We can probably post-process the YAML files using the `.manifest` file to work out which UIDs are actually in the package. It seems odd that we have to do that (and it'll be pretty ugly), but if it works, it works.
